cpp_files=sim_main.cpp
files=../src/AXI4LiteConverter.v
includepaths=
defines=-DDEBUG_CLINT
verilator_options=-Wno-UNOPTFLAT -Wno-DECLFILENAME # -LDFLAGS "-ggdb" -CFLAGS "-ggdb"
top=AXI4LiteConverter
OPT=-ggdb
include VerilatorSimulate.mk